#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Install any missing dependencies since package.json changed
git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet package.json && npm ci
