#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set +e
# Install any missing dependencies since package.json changed, while only versions changes are ignored.
git diff-tree -r --ignore-matching-lines="version" --name-only --no-commit-id "$1" "$2" | grep --quiet package.json && npm ci
set -e
