name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      HUSKY: 0 # Disable husky and git-hooks
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Package
        run: npm run build
      - name: Release Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release:ci
